"""initial_schema

Revision ID: b440565041fb
Revises: 
Create Date: 2026-07-06 11:49:50.067391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b440565041fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mrp_exception_id'), table_name='mrp_exception')
    op.drop_table('mrp_exception')
    op.drop_index(op.f('payment_number'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('customer_code'), table_name='customer')
    op.drop_table('customer')
    op.drop_index(op.f('order_number'), table_name='sales_order')
    op.drop_table('sales_order')
    op.alter_column('work_order_material', 'required_qty',
               existing_type=mysql.FLOAT(),
               nullable=False,
               comment='需求数量',
               existing_server_default=sa.text("'0'"))
    op.alter_column('work_order_material', 'issued_qty',
               existing_type=mysql.FLOAT(),
               comment='已发料数量',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('work_order_material', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_foreign_key(None, 'work_order_material', 'material_master', ['item_id'], ['id'])
    op.create_foreign_key(None, 'work_order_material', 'work_order', ['work_order_id'], ['id'])
    op.create_foreign_key(None, 'work_order_material', 'bom_line', ['bom_line_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_order_material', type_='foreignkey')
    op.drop_constraint(None, 'work_order_material', type_='foreignkey')
    op.drop_constraint(None, 'work_order_material', type_='foreignkey')
    op.alter_column('work_order_material', 'created_at',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('work_order_material', 'issued_qty',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='已发料数量',
               existing_nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('work_order_material', 'required_qty',
               existing_type=mysql.FLOAT(),
               nullable=True,
               comment=None,
               existing_comment='需求数量',
               existing_server_default=sa.text("'0'"))
    op.create_table('sales_order',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='销售订单号'),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='产品物料'),
    sa.Column('order_qty', mysql.FLOAT(), nullable=False, comment='订单数量'),
    sa.Column('shipped_qty', mysql.FLOAT(), nullable=True, comment='已出货数量'),
    sa.Column('unit_price', mysql.FLOAT(), nullable=True, comment='单价'),
    sa.Column('total_amount', mysql.FLOAT(), nullable=True, comment='订单总金额'),
    sa.Column('paid_amount', mysql.FLOAT(), nullable=True, comment='已收款金额'),
    sa.Column('delivery_date', sa.DATE(), nullable=False, comment='交期'),
    sa.Column('ship_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='出货状态: 待出货/部分出货/全部出货'),
    sa.Column('pay_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='收款状态: 未收款/部分收款/全部收款'),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='综合状态: 进行中/已完成/已取消'),
    sa.Column('priority', mysql.INTEGER(), autoincrement=False, nullable=True, comment='优先级'),
    sa.Column('source_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='来源'),
    sa.Column('remark', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('sales_order_ibfk_1')),
    sa.ForeignKeyConstraint(['item_id'], ['material_master.id'], name=op.f('sales_order_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('order_number'), 'sales_order', ['order_number'], unique=True)
    op.create_table('customer',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='客户编码'),
    sa.Column('customer_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False, comment='客户名称'),
    sa.Column('contact_person', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('contact_phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('remark', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('customer_code'), 'customer', ['customer_code'], unique=True)
    op.create_table('payment',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('payment_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False, comment='收款单号'),
    sa.Column('sales_order_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='关联销售订单'),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=False, comment='客户'),
    sa.Column('amount', mysql.FLOAT(), nullable=False, comment='收款金额'),
    sa.Column('payment_date', sa.DATE(), nullable=True, comment='收款日期'),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='状态: 未到账/已到账/部分到账'),
    sa.Column('payment_method', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=True, comment='付款方式'),
    sa.Column('remark', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name=op.f('payment_ibfk_2')),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], name=op.f('payment_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('payment_number'), 'payment', ['payment_number'], unique=True)
    op.create_table('mrp_exception',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('run_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True, comment='MRP运行批次ID'),
    sa.Column('exception_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=True, comment='例外类型: SHORTAGE/OVERDUE_ORDER/SAFETY_STOCK_ALERT/SUBSTITUTE'),
    sa.Column('item_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True, comment='物料编码'),
    sa.Column('material_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True, comment='物料型号'),
    sa.Column('message', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True, comment='例外描述'),
    sa.Column('severity', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='严重程度: ERROR/WARNING/INFO'),
    sa.Column('is_resolved', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='是否已处理'),
    sa.Column('resolved_at', mysql.DATETIME(), nullable=True, comment='处理时间'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_mrp_exception_id'), 'mrp_exception', ['id'], unique=False)
    # ### end Alembic commands ###
